on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git log | head
      - name: build image
        run: docker build -t test-git .
