on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${GITHUB_REF#refs/*/}"
      - name: build image
        run: docker build -t test-git .
